# Generated by Django 5.1.6 on 2025-05-21 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_options_remove_user_date_joined_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='unidade_curricular',
        ),
    ]
