# Generated by Django 5.1.6 on 2025-05-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_horario_unidade_curricular'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='ano_letivo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
