# Generated by Django 5.1.6 on 2025-06-17 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_coordenador_user_departamento_and_more'),  # Substitua por sua migração anterior real
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
    ]