# Generated by Django 5.2.3 on 2025-06-17 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_unused_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordenador',
            name='cargo_status',
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.DeleteModel(
            name='Horario',
        ),
    ]
