# Generated by Django 5.2.3 on 2025-06-20 22:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_coordenador_cargo_status_user_last_login_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='aprovacaodisponibilidade',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='coordenador',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='user',
            name='coordenador',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nome',
        ),
        migrations.AddField(
            model_name='aprovacaodisponibilidade',
            name='coordenador_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aprovacoes_feitas_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disponibilidade',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='api.docente'),
        ),
        migrations.AddField(
            model_name='disponibilidade',
            name='intervalo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='aprovacaodisponibilidade',
            name='coordenador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aprovacoes_feitas', to='api.coordenador'),
        ),
        migrations.AlterField(
            model_name='coordenador',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_coordenador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to='api.escola'),
        ),
        migrations.AlterField(
            model_name='disponibilidade',
            name='dia',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='disponibilidade',
            name='hora_fim',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disponibilidade',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disponibilidade',
            name='utilizador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades_antigas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='docente',
            name='coordenador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docentes_supervisionados', to='api.coordenador'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_docente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='api.departamento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='tipo_conta',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('coordenador', 'Coordenador'), ('docente', 'Docente'), ('admin', 'Administrador')], default='pendente', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='aprovacaodisponibilidade',
            unique_together={('disponibilidade', 'coordenador_user')},
        ),
    ]
