# Generated by Django 5.2.3 on 2025-06-20 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_user_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='nome',
        ),
    ]
