# Generated by Django 5.2.3 on 2025-06-20 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_username_user_nome'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='aprovacaodisponibilidade',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='disponibilidade',
            name='ano_letivo',
        ),
        migrations.RemoveField(
            model_name='disponibilidade',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='disponibilidade',
            name='hora_fim',
        ),
        migrations.RemoveField(
            model_name='disponibilidade',
            name='hora_inicio',
        ),
        migrations.RemoveField(
            model_name='disponibilidade',
            name='utilizador',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='aprovacaodisponibilidade',
            name='coordenador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aprovacoes', to='api.coordenador'),
        ),
        migrations.AlterField(
            model_name='coordenador',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coordenador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='docente',
            name='coordenador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docentes', to='api.coordenador'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='docente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='aprovacaodisponibilidade',
            name='coordenador_user',
        ),
    ]
