# Generated by Django 5.2.3 on 2025-06-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_aprovacaodisponibilidade_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidade',
            name='ano_letivo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='disponibilidade',
            name='dia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disponibilidade',
            name='hora_fim',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disponibilidade',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
