# Generated by Django 5.2.3 on 2025-06-21 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_disponibilidade_ano_letivo_disponibilidade_dia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='escola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to='api.escola'),
        ),
    ]
