# Generated by Django 5.2.3 on 2025-06-21 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_departamento_escola'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='escola',
        ),
        migrations.AddField(
            model_name='escola',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escolas', to='api.departamento'),
        ),
    ]
