# Generated by Django 5.2.3 on 2025-06-22 05:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_departamento_escola_escola_departamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(default=django.utils.timezone.now)),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('semestre', models.CharField(blank=True, max_length=20, null=True)),
                ('ano_letivo', models.CharField(blank=True, max_length=20, null=True)),
                ('utilizador', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('disponibilidade_aprovada', 'Disponibilidade Aprovada'), ('disponibilidade_rejeitada', 'Disponibilidade Rejeitada'), ('horario_criado', 'Horário Criado'), ('docente_adicionado', 'Docente Adicionado'), ('coordenador_atribuido', 'Coordenador Atribuído'), ('departamento_alterado', 'Departamento Alterado'), ('geral', 'Geral')], max_length=30)),
                ('titulo', models.CharField(max_length=255)),
                ('mensagem', models.TextField()),
                ('lida', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('disponibilidade_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.disponibilidade')),
                ('horario_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.horario')),
                ('user_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_referencia', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
    ]
