from django.urls import path
from .views import (
    CoordenadorListView, CoordenadorUpdateView, CoordenadorPerfilView, CoordenadorAlterarNomeView,
    DepartamentoListCreateView, DepartamentoUpdateDeleteView, 
    DocenteListView, DocenteUpdateView, DocentePerfilView, DocenteAlterarNomeView,
    EscolaListCreateView, EscolaUpdateDeleteView, 
    LoginView, RegistoView, SubmeterDisponibilidadeView, UserTipoContaView, 
    UserTipoContaUpdateView, 
    ListUsersView, VisualizarHorarioView, ConsultarDisponibilidadesView, 
    GerenciarAprovacaoView, UserInfoView, ExportarHorarioView, 
    VisualizarHorarioDocenteView, ExportarHorarioDocenteView, VerificarDepartamentoDocenteView
)

urlpatterns = [
    path('registo', RegistoView.as_view(), name='registo'),
    path('login', LoginView.as_view(), name='login'),
    path('user/tipo-conta', UserTipoContaView.as_view(), name='user-tipo-conta'),
    path('user/tipo-conta/<int:id>/update', UserTipoContaUpdateView.as_view(), name='user-tipo-conta-update'),
    path('users/list', ListUsersView.as_view(), name='list-users'),
    path('escolas', EscolaListCreateView.as_view(), name='escolas-list-create'),
    path('escolas/<int:id>', EscolaUpdateDeleteView.as_view(), name='escolas-update-view'),   
    path('departamentos', DepartamentoListCreateView.as_view(), name='departamentos-list-create'),
    path('departamentos/<int:id>', DepartamentoUpdateDeleteView.as_view(), name='departamentos-update-delete'),
    path('coordenadores', CoordenadorListView.as_view(), name='coordenadores-list'),
    path('coordenadores/<int:id>', CoordenadorUpdateView.as_view(), name='coordenador-update'),
    path('coordenador/perfil', CoordenadorPerfilView.as_view(), name='coordenador-perfil'),
    path('coordenador/alterar-nome', CoordenadorAlterarNomeView.as_view(), name='coordenador-alterar-nome'),
    path('docentes', DocenteListView.as_view(), name='docentes-list'),
    path('docentes/<int:id>', DocenteUpdateView.as_view(), name='docente-update'),
    path('docente/perfil', DocentePerfilView.as_view(), name='docente-perfil'),
    path('docente/alterar-nome', DocenteAlterarNomeView.as_view(), name='docente-alterar-nome'),
    path('submeter-disponibilidade', SubmeterDisponibilidadeView.as_view(), name='submeter-disponibilidade'),
    path('submeter-disponibilidade/<int:id>', SubmeterDisponibilidadeView.as_view(), name='deletar-disponibilidade'),
    path('visualizar-horario', VisualizarHorarioView.as_view(), name='visualizar-horario'),
    path('user/info', UserInfoView.as_view(), name='user-info'),
    path('consultar-disponibilidades', ConsultarDisponibilidadesView.as_view(), name='consultar-disponibilidades'),
    path('gerenciar-aprovacao', GerenciarAprovacaoView.as_view(), name='gerenciar-aprovacao'),
    path('exportar-horario', ExportarHorarioView.as_view(), name='exportar-horario'),
    path('visualizar-horario-docente', VisualizarHorarioDocenteView.as_view(), name='visualizar-horario-docente'),
    path('exportar-horario-docente', ExportarHorarioDocenteView.as_view(), name='exportar-horario-docente'),
    path('verificar-departamento-docente', VerificarDepartamentoDocenteView.as_view(), name='verificar-departamento-docente'),
]