services:
  web:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    command: >
        sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
      
    volumes:
      - ./Backend:/app
      # Excluir cache Python
      - /app/__pycache__
      - /app/*/__pycache__
    ports:
      - "8000:8000"
    env_file:
      - ./Backend/.env
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_RELOAD=True
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: P017
      POSTGRES_USER: bruno
      POSTGRES_PASSWORD: 123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bruno -d P017"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  react-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    restart: unless-stopped
    depends_on:
      - web
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  postgres_data: